# Generated by Django 6.0.6 on 2026-07-04 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ordem', models.IntegerField()),
                ('idade_minima', models.IntegerField()),
                ('tempo_minimo_meses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('avaliadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.faixa')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('data_inicio', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('foto', models.ImageField(blank=True, upload_to='alunos/')),
                ('faixa_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jjcoral.faixa')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('nota_tecnica', models.IntegerField(blank=True, null=True)),
                ('nota_postura', models.IntegerField(blank=True, null=True)),
                ('nota_disciplina', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.aluno')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.exame')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.aluno')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treino',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jjcoral.turma'),
        ),
    ]
