# Generated by Django 6.0.6 on 2026-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjcoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='jjcoral.aluno'),
        ),
    ]
