# Generated by Django 6.0.6 on 2026-07-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjcoral', '0002_turma_alunos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='observacoes',
            new_name='resultado',
        ),
        migrations.AddField(
            model_name='exame',
            name='aluno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jjcoral.aluno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/'),
        ),
    ]
